### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by AndreFCruz** [antonioalmeida/feup-plog#3]
Instructions unclear
![unknown](https://user-images.githubusercontent.com/13498941/38136380-ec046b52-3415-11e8-9d62-1345f21dc543.png)

**Comment by cyrilico** [comment]
readmeIsGood.
readmeIsGood:- readmeIsGood.

**Comment by cyrilico** [comment]
@AndreFCruz please tackle or close issue

**Comment by AndreFCruz** [comment]
Closed due to inactivity and fire no longer existing
